// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type Url struct {
	ID          int64
	Slug        string
	OriginalUrl string
	ClickCount  int64
	CreatedAt   time.Time
}
