// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountSlugs(ctx context.Context) (int64, error)
	GetBySlug(ctx context.Context, slug string) (string, error)
	GetStats(ctx context.Context, slug string) (GetStatsRow, error)
	IncrementClicks(ctx context.Context, slug string) error
	InsertUrl(ctx context.Context, arg InsertUrlParams) (sql.Result, error)
	ListSlugsPaginated(ctx context.Context, arg ListSlugsPaginatedParams) ([]ListSlugsPaginatedRow, error)
}

var _ Querier = (*Queries)(nil)
