// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const getBySlug = `-- name: GetBySlug :one
SELECT original_url FROM urls
WHERE slug = ?
`

func (q *Queries) GetBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRowContext(ctx, getBySlug, slug)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}

const getStats = `-- name: GetStats :one
SELECT original_url, click_count, created_at FROM urls
WHERE slug = ?
`

type GetStatsRow struct {
	OriginalUrl string
	ClickCount  int64
	CreatedAt   time.Time
}

func (q *Queries) GetStats(ctx context.Context, slug string) (GetStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getStats, slug)
	var i GetStatsRow
	err := row.Scan(&i.OriginalUrl, &i.ClickCount, &i.CreatedAt)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE urls SET click_count = click_count + 1
WHERE slug = ?
`

func (q *Queries) IncrementClicks(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, incrementClicks, slug)
	return err
}

const insertUrl = `-- name: InsertUrl :execresult
INSERT INTO urls (slug, original_url)
VALUES (?, ?)
`

type InsertUrlParams struct {
	Slug        string
	OriginalUrl string
}

func (q *Queries) InsertUrl(ctx context.Context, arg InsertUrlParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertUrl, arg.Slug, arg.OriginalUrl)
}

const listSlugs = `-- name: ListSlugs :many
SELECT slug, original_url, click_count, created_at FROM urls
ORDER BY created_at DESC
`

type ListSlugsRow struct {
	Slug        string
	OriginalUrl string
	ClickCount  int64
	CreatedAt   time.Time
}

func (q *Queries) ListSlugs(ctx context.Context) ([]ListSlugsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSlugsRow
	for rows.Next() {
		var i ListSlugsRow
		if err := rows.Scan(
			&i.Slug,
			&i.OriginalUrl,
			&i.ClickCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
